---
title: "Quantitative Genetics in AlphaSimR"
author: "Gregor Gorjanc and Chris Gaynor"
date: "`r Sys.Date()`"
output: rmarkdown::pdf_document
tables: true
bibliography: AlphaSimR.bib
vignette: >
  %\VignetteIndexEntry{Quantitative Genetics}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

# Introduction

This vignette describes how AlphaSimR implements quantitative genetics theory. This vignette is based on AlphaSimR's trait definition, so you should be familiar with the "traits" vignette. The implementation of quantitative genetics theory will be described by following description and examples from Falconer and Mackay [-@FalconerMackay] and then tweaking the examples to demonstrate various assumptions and deviations from the assumptions.

# Single-locus **AD** trait

TODO: Summarize Falconer's exposition ...

\begin{equation}
P(x) = 
\mu + 
G(x) +
E(x) +
\end{equation}

$P(x)$ is the phenotypic value of an individual with genotype dosage $x$ at a single locus.

```{r}
  # P_HW = p^2 +a -->
  # H_HW = 2pq  d
  # Q_HW = q^2 -a
  # p^2 +a + 2pq  d + q^2 -a + intercept
  p[1]^2 * a[1] + 2 * p[1] * q[1] * d[1] + q[1]^2 * -a[1] + 10
  P[1] * a[1] + H[1] * d[1] + Q[1] * -a[1] + 10

  p[3]^2 * a[3] + 2 * p[3] * q[3] * d[3] + q[3]^2 * -a[3] + 10
  P[3] * a[3] + H[3] * d[3] + Q[3] * -a[3] + 10

  c(p[3]^2, 2 * p[3] * q[3], q[3]^2)
  c(P[3], H[3], Q[3])
  c(
    p[3]^2 + p[3] * q[3] * F[3],
    2 * p[3] * q[3] - 2 * p[3] * q[3] * F[3],
    q[3]^2 + p[3] * q[3] * F[3]
  )

  p[1]^2 * a[1] + 2 * p[1] * q[1] * d[1] + q[1]^2 * -a[1] + 10

```

\begin{equation}
P(x) = 
\mu + 
A(x) +
D(x) +
E(x) +
\end{equation}

\begin{equation}
x_A = \big( x - \tfrac{ploidy}{2} \big) \big( \tfrac{2}{ploidy} \big)
\end{equation}

\begin{equation}
A(x) = \sum a x_A
\end{equation}

\begin{equation}
d = \delta \left| a \right|
\end{equation}

Table 1 TODO

\begin{table}[h]
\centering
\caption{Raw and scaled genotype dosages.}
\begin{tabular}{@{}rrrr@{}}
\toprule
Diploid & Tetraploid & Additive & Dominance \\ \midrule
0 & 0 & $-1$ & $0$ \\
 & 1 & $-1/2$ & $3/4$ \\
1 & 2 & $0$ & $1$ \\
 & 3 & $1/2$ & $3/4$ \\
2 & 4 & $1$ & $0$ \\ \bottomrule
\end{tabular}
\end{table}

R code `runif

# Two-locus **ADE** trait

# References
