context("addTrait")

test_that("addTraitA",{
  genMap = list(c(0))
  founderPop = trackHaploPop(genMap=genMap,nInd=2,inbred=TRUE)
  SP = SimParam$new(founderPop=founderPop)
  SP$addTraitA(nQtlPerChr=1,mean=0,var=1)
  pop = newPop(founderPop,simParam=SP)
  expect_equal(abs(SP$traits[[1]]@addEff),1,tolerance=1e-6)
  expect_equal(abs(SP$traits[[1]]@intercept),1,tolerance=1e-6)
  expect_equal(SP$varA,1,tolerance=1e-6)
  expect_equal(SP$varG,1,tolerance=1e-6)
  expect_equal(c(varA(pop,simParam=SP)),1,tolerance=1e-6)
  expect_equal(c(varD(pop,simParam=SP)),0,tolerance=1e-6)
  expect_equal(c(varG(pop)),1,tolerance=1e-6)
  expect_equal(genicVarA(pop,simParam=SP),0.5,tolerance=1e-6)
  expect_equal(genicVarD(pop,simParam=SP),0,tolerance=1e-6)
  expect_equal(genicVarG(pop,simParam=SP),0.5,tolerance=1e-6)
})

test_that("addTraitAD",{
  genMap = list(c(0))
  founderPop = trackHaploPop(genMap=genMap,nInd=2,inbred=TRUE)
  SP = SimParam$new(founderPop=founderPop)
  SP$addTraitAD(nQtlPerChr=1,mean=0,var=1,meanDD=1)
  pop = newPop(founderPop,simParam=SP)
  expect_equal(abs(SP$traits[[1]]@addEff),1,tolerance=1e-6)
  expect_equal(SP$traits[[1]]@domEff,1,tolerance=1e-6)
  expect_equal(abs(SP$traits[[1]]@intercept),1,tolerance=1e-6)
  expect_equal(SP$varA,1,tolerance=1e-6)
  expect_equal(SP$varG,1,tolerance=1e-6)
  expect_equal(c(varA(pop,simParam=SP)),1,tolerance=1e-6)
  expect_equal(c(varD(pop,simParam=SP)),0,tolerance=1e-6)
  expect_equal(c(varG(pop)),1,tolerance=1e-6)
  expect_equal(genicVarA(pop,simParam=SP),0.5,tolerance=1e-6)
  expect_equal(genicVarD(pop,simParam=SP),0.25,tolerance=1e-6)
  expect_equal(genicVarG(pop,simParam=SP),0.75,tolerance=1e-6)
})

test_that("addTraitAG",{
  genMap = list(c(0))
  founderPop = trackHaploPop(genMap=genMap,nInd=2,inbred=TRUE)
  SP = SimParam$new(founderPop=founderPop)
  SP$addTraitAG(nQtlPerChr=1,mean=0,var=1,varEnv=1,varGxE=1)
  pop = newPop(founderPop,simParam=SP)
  expect_equal(abs(SP$traits[[1]]@addEff),1,tolerance=1e-6)
  expect_equal(abs(SP$traits[[1]]@gxeEff),1,tolerance=1e-6)
  expect_equal(SP$traits[[1]]@envVar,1,tolerance=1e-6)
  expect_equal(abs(SP$traits[[1]]@gxeInt-1),1,tolerance=1e-6)
  expect_equal(abs(SP$traits[[1]]@intercept),1,tolerance=1e-6)
  expect_equal(SP$varA,1,tolerance=1e-6)
  expect_equal(SP$varG,1,tolerance=1e-6)
  expect_equal(c(varA(pop,simParam=SP)),1,tolerance=1e-6)
  expect_equal(c(varD(pop,simParam=SP)),0,tolerance=1e-6)
  expect_equal(c(varG(pop)),1,tolerance=1e-6)
  expect_equal(genicVarA(pop,simParam=SP),0.5,tolerance=1e-6)
  expect_equal(genicVarD(pop,simParam=SP),0,tolerance=1e-6)
  expect_equal(genicVarG(pop,simParam=SP),0.5,tolerance=1e-6)
})

test_that("addTraitADG",{
  genMap = list(c(0))
  founderPop = trackHaploPop(genMap=genMap,nInd=2,inbred=TRUE)
  SP = SimParam$new(founderPop=founderPop)
  SP$addTraitADG(nQtlPerChr=1,mean=0,var=1,meanDD=1,varEnv=1,varGxE=1)
  pop = newPop(founderPop,simParam=SP)
  expect_equal(abs(SP$traits[[1]]@addEff),1,tolerance=1e-6)
  expect_equal(SP$traits[[1]]@domEff,1,tolerance=1e-6)
  expect_equal(abs(SP$traits[[1]]@gxeEff),1,tolerance=1e-6)
  expect_equal(SP$traits[[1]]@envVar,1,tolerance=1e-6)
  expect_equal(abs(SP$traits[[1]]@gxeInt-1),1,tolerance=1e-6)
  expect_equal(abs(SP$traits[[1]]@intercept),1,tolerance=1e-6)
  expect_equal(SP$varA,1,tolerance=1e-6)
  expect_equal(SP$varG,1,tolerance=1e-6)
  expect_equal(c(varA(pop,simParam=SP)),1,tolerance=1e-6)
  expect_equal(c(varD(pop,simParam=SP)),0,tolerance=1e-6)
  expect_equal(c(varG(pop)),1,tolerance=1e-6)
  expect_equal(genicVarA(pop,simParam=SP),0.5,tolerance=1e-6)
  expect_equal(genicVarD(pop,simParam=SP),0.25,tolerance=1e-6)
  expect_equal(genicVarG(pop,simParam=SP),0.75,tolerance=1e-6)
})
