context("crossing")

test_that("makeCross",{
  genMap = list(c(0))
  founderPop = trackHaploPop(genMaps=genMap,nInd=2,inbred=TRUE)
  SP = SimParam$new(founderPop=founderPop)
  SP$addTraitA(nQtlPerChr=1,mean=0,var=1)
  SP$setTrackPed(TRUE)
  pop = newPop(founderPop,simParam=SP)
  crossPlan = cbind(rep(1,10),rep(2,10))
  #Match by number
  pop0 = makeCross(pop=pop,crossPlan=crossPlan,rawPop=TRUE,simParam=SP)
  expect_equal(SP$lastId,2L)
  pop1 = makeCross(pop=pop,crossPlan=crossPlan,simParam=SP)
  expect_equal(SP$lastId,12L)
  expect_equal(meanG(pop1),0,tolerance=1e-6)
  expect_equal(SP$pedigree[-(1:2),1L],rep(1L,10L))
  expect_equal(SP$pedigree[-(1:2),2L],rep(2L,10L))
  #Match by id
  crossPlan = matrix(as.character(crossPlan),ncol=2)
  pop2 = makeCross(pop=pop,crossPlan=crossPlan,simParam=SP)
  expect_equal(SP$lastId,22L)
  expect_equal(meanG(pop2),0,tolerance=1e-6)
  expect_equal(SP$pedigree[-(1:2),1L],rep(1L,20L))
  expect_equal(SP$pedigree[-(1:2),2L],rep(2L,20L))
})

test_that("makeCross2",{
  genMap = list(c(0))
  founderPop = trackHaploPop(genMaps=genMap,nInd=2,inbred=TRUE)
  SP = SimParam$new(founderPop=founderPop)
  SP$addTraitA(nQtlPerChr=1,mean=0,var=1)
  SP$setTrackPed(TRUE)
  pop = newPop(founderPop,simParam=SP)
  crossPlan = cbind(rep(1,10),rep(2,10))
  #Match by number
  pop0 = makeCross2(females=pop,males=pop,crossPlan=crossPlan,rawPop=TRUE,simParam=SP)
  expect_equal(SP$lastId,2L)
  pop1 = makeCross2(females=pop,males=pop,crossPlan=crossPlan,simParam=SP)
  expect_equal(SP$lastId,12L)
  expect_equal(meanG(pop1),0,tolerance=1e-6)
  expect_equal(SP$pedigree[-(1:2),1L],rep(1L,10L))
  expect_equal(SP$pedigree[-(1:2),2L],rep(2L,10L))
  #Match by id
  crossPlan = matrix(as.character(crossPlan),ncol=2)
  pop2 = makeCross2(females=pop,males=pop,crossPlan=crossPlan,simParam=SP)
  expect_equal(SP$lastId,22L)
  expect_equal(meanG(pop2),0,tolerance=1e-6)
  expect_equal(SP$pedigree[-(1:2),1L],rep(1L,20L))
  expect_equal(SP$pedigree[-(1:2),2L],rep(2L,20L))
})

test_that("randCross",{
  genMap = list(c(0))
  founderPop = trackHaploPop(genMaps=genMap,nInd=2,inbred=TRUE)
  SP = SimParam$new(founderPop=founderPop)
  SP$addTraitA(nQtlPerChr=1,mean=0,var=1)
  SP$setTrackPed(TRUE)
  SP$setGender("yes_sys")
  pop = newPop(founderPop,simParam=SP)
  crossPlan = cbind(rep(1,10),rep(2,10))
  pop0 = randCross(pop=pop,nCrosses=1,nProgeny=10,rawPop=TRUE,simParam=SP)
  expect_equal(SP$lastId,2L)
  pop1 = randCross(pop=pop,nCrosses=1,nProgeny=10,simParam=SP)
  expect_equal(SP$lastId,12L)
  expect_equal(meanG(pop1),0,tolerance=1e-6)
  expect_equal(SP$pedigree[-(1:2),1L],rep(2L,10L))
  expect_equal(SP$pedigree[-(1:2),2L],rep(1L,10L))
})

test_that("randCross2",{
  genMap = list(c(0))
  founderPop = trackHaploPop(genMaps=genMap,nInd=2,inbred=TRUE)
  SP = SimParam$new(founderPop=founderPop)
  SP$addTraitA(nQtlPerChr=1,mean=0,var=1)
  SP$setTrackPed(TRUE)
  SP$setGender("yes_sys")
  pop = newPop(founderPop,simParam=SP)
  crossPlan = cbind(rep(1,10),rep(2,10))
  pop0 = randCross2(females=pop,males=pop,nCrosses=1,nProgeny=10,rawPop=TRUE,simParam=SP)
  expect_equal(SP$lastId,2L)
  pop1 = randCross2(females=pop,males=pop,nCrosses=1,nProgeny=10,simParam=SP)
  expect_equal(SP$lastId,12L)
  expect_equal(meanG(pop1),0,tolerance=1e-6)
  expect_equal(SP$pedigree[-(1:2),1L],rep(2L,10L))
  expect_equal(SP$pedigree[-(1:2),2L],rep(1L,10L))
})

test_that("self",{
  genMap = list(c(0))
  founderPop = trackHaploPop(genMaps=genMap,nInd=2,inbred=TRUE)
  SP = SimParam$new(founderPop=founderPop)
  SP$addTraitA(nQtlPerChr=1,mean=0,var=1)
  SP$setTrackPed(TRUE)
  pop = newPop(founderPop,simParam=SP)
  crossPlan = cbind(rep(1,10),rep(2,10))
  pop0 = self(pop=pop,nProgeny=1,rawPop=TRUE,simParam=SP)
  expect_equal(SP$lastId,2L)
  pop1 = self(pop=pop,nProgeny=1,simParam=SP)
  expect_equal(SP$lastId,4L)
  expect_equal(meanG(pop1),0,tolerance=1e-6)
  expect_equal(SP$pedigree[-(1:2),1L],c(1L,2L))
  expect_equal(SP$pedigree[-(1:2),2L],c(1L,2L))
  expect_equal(SP$pedigree[-(1:2),3L],c(0L,0L))
})

test_that("makeDH",{
  genMap = list(c(0))
  founderPop = trackHaploPop(genMaps=genMap,nInd=2,inbred=TRUE)
  SP = SimParam$new(founderPop=founderPop)
  SP$addTraitA(nQtlPerChr=1,mean=0,var=1)
  SP$setTrackPed(TRUE)
  pop = newPop(founderPop,simParam=SP)
  crossPlan = cbind(rep(1,10),rep(2,10))
  pop0 = makeDH(pop=pop,nDH=1,rawPop=TRUE,simParam=SP)
  expect_equal(SP$lastId,2L)
  pop1 = makeDH(pop=pop,nDH=1,simParam=SP)
  expect_equal(SP$lastId,4L)
  expect_equal(meanG(pop1),0,tolerance=1e-6)
  expect_equal(SP$pedigree[-(1:2),1L],c(1L,2L))
  expect_equal(SP$pedigree[-(1:2),2L],c(1L,2L))
  expect_equal(SP$pedigree[-(1:2),3L],c(1L,1L))
})

test_that("selectCross",{
  genMap = list(c(0))
  founderPop = trackHaploPop(genMaps=genMap,nInd=2,inbred=TRUE)
  SP = SimParam$new(founderPop=founderPop)
  SP$addTraitA(nQtlPerChr=1,mean=0,var=1)
  SP$setTrackPed(TRUE)
  SP$setGender("yes_sys")
  pop = newPop(founderPop,simParam=SP)
  pop1 = selectCross(pop=pop,nFemale=1,nMale=1,use="rand",nCrosses=2,simParam=SP)
  expect_equal(SP$lastId,4L)
  expect_equal(meanG(pop1),0,tolerance=1e-6)
  expect_equal(SP$pedigree[-(1:2),1L],c(2L,2L))
  expect_equal(SP$pedigree[-(1:2),2L],c(1L,1L))
})