---
title: "Simple Genetic Simulations"
author: "Chris Gaynor"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

In this vignette I will show how genetic simulations work using a simple examples. 
I will start by showing how to simulate phenotypes from genotypes. I will then 
show how to simulate new genotypes from existing genotypes.

## Simulating phenotypes from genotypes

Simulating phenotypes from genotypes is a straightforward process that can be 
done fairly easily using just base R functionality. 



-Simulate inbred genotypes

-Simulate QTL effects

-Calculate genetic values
-Scale genetic values to desired variance
-Shift mean

-Simulate phenotypes


## Simulating new genotypes

-Describe meiosis
-Break genotypes into haplotypes
-Create F1 by pairing chromosomes
-Assign loci to a genetic map
-Randomly choose a starting chromosome
-Model recombination





