# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

AlphaFormatter <- function() {
    .Call('AlphaSimR_AlphaFormatter', PACKAGE = 'AlphaSimR')
}

getGeno <- function(pop, lociPerChr, lociLoc) {
    .Call('AlphaSimR_getGeno', PACKAGE = 'AlphaSimR', pop, lociPerChr, lociLoc)
}

getDomGeno <- function(geno) {
    .Call('AlphaSimR_getDomGeno', PACKAGE = 'AlphaSimR', geno)
}

calcGvA <- function(geno, a, intercept) {
    .Call('AlphaSimR_calcGvA', PACKAGE = 'AlphaSimR', geno, a, intercept)
}

getGvA <- function(trait, pop) {
    .Call('AlphaSimR_getGvA', PACKAGE = 'AlphaSimR', trait, pop)
}

calcGvAD <- function(geno, a, d, intercept) {
    .Call('AlphaSimR_calcGvAD', PACKAGE = 'AlphaSimR', geno, a, d, intercept)
}

getGvAD <- function(trait, pop) {
    .Call('AlphaSimR_getGvAD', PACKAGE = 'AlphaSimR', trait, pop)
}

calcGenParam <- function(trait, pop, a, d) {
    .Call('AlphaSimR_calcGenParam', PACKAGE = 'AlphaSimR', trait, pop, a, d)
}

cross2 <- function(fGeno, fPar, mGeno, mPar, genMaps) {
    .Call('AlphaSimR_cross2', PACKAGE = 'AlphaSimR', fGeno, fPar, mGeno, mPar, genMaps)
}

readAF <- function(nHap, segSites, keep) {
    .Call('AlphaSimR_readAF', PACKAGE = 'AlphaSimR', nHap, segSites, keep)
}

tuneTraitA <- function(geno, addEff, varG) {
    .Call('AlphaSimR_tuneTraitA', PACKAGE = 'AlphaSimR', geno, addEff, varG)
}

tuneTraitAD <- function(geno, addEff, domEff, varG) {
    .Call('AlphaSimR_tuneTraitAD', PACKAGE = 'AlphaSimR', geno, addEff, domEff, varG)
}

